### ISSUE TITLE
name.check is not case sensitive!

### ISSUE THREAD

**Issue by achazhardenberg** [mwpennell/geiger-v2#41] opened 2020-02-18 19:54 UTC
Hi,
I just found out that name.check() will give an "OK" even if a species name is erroneously capitalised like in Callithrix_Jacchus instead of Callithrix_jacchus in the dataframe but not in the tree. This is a problem for various other packages which are instead case sensitive for the species names.

**Comment by liamrevell** [comment] 2020-05-07 02:03
I'm unable to reproduce this error. For instance:
`> ## control
> tree<-pbtree(n=26,tip.label=LETTERS)
> x<-fastBM(tree)
> name.check(tree,x)
[1] "OK"
> X<-data.frame(x=x)
> name.check(tree,X)
[1] "OK"
> ## substitute names
> tree$tip.label[1]<-"Callithrix_Jacchus"
> names(x)[1]<-"Callithrix_jacchus"
> name.check(tree,x)
$tree_not_data
[1] "Callithrix_Jacchus"

$data_not_tree
[1] "Callithrix_jacchus"

> X<-data.frame(x=x)
> name.check(tree,X)
$tree_not_data
[1] "Callithrix_Jacchus"

$data_not_tree
[1] "Callithrix_jacchus"`

**Comment by lukejharmon** [comment] 2020-05-26 17:30
I agree with Liam's assessment, and will close this issue. If you can confirm with a code block that produces this error, that would be great - and I will reopen in that case.

**Closed by lukejharmon** 2020-05-26 17:30 UTC
