### ISSUE TITLE
fitContinuousMCMC: Error in solve.default(C):  Lapack routine dgesv: 

### ISSUE THREAD

**Issue by jjsolano** [mwpennell/geiger-v2#37] opened 2019-08-21 22:30 UTC
Hi, 

I'm try to run fitContinuousMCMC function with several traits (around 600 datasets). I'm attaching 6 of them as example [here](https://www.dropbox.com/sh/n69yuxwsbqhi324/AABDqbtjgBWRKbDuMf3elsHia?dl=0): 

In some cases I get the follow message:
_Error in solve.default(C) :  Lapack routine dgesv: system is exactly singular: U[967,967] = 0_

I have the same error on several of my datasets. 

I appreciate any help.

Regards,

**Comment by oftheleft0** [comment] 2020-04-17 18:27
I am experiencing the same error, though it is not resolved by changing sample.node.states. It seems to be caused by zero branch lengths introduced when forcing polytomies into bifurcations. It's resolved by adding an arbitrarily small value to these branch lengths, but is there a better way to handle this issue?

**Comment by oftheleft0** [comment] 2020-04-17 18:28
I am experiencing the same error, though it is not resolved by changing sample.node.states. It seems to be caused by zero branch lengths introduced when forcing polytomies into bifurcations. It's resolved by adding an arbitrarily small value to these branch lengths, but is there a better way to handle this issue?

**Comment by lukejharmon** [comment] 2020-05-26 17:40
I don't think there is a better way to handle this issue other than a deep dive into this code- which is not being actively developed. So, I think the best we can advise for anyone here is to set sample.node.states=FALSE and set zero length branches to a small value.

**Closed by lukejharmon** 2020-05-26 17:40 UTC
